### Numpy Library
- Processing N-Dimensional arrays

In [5]:
import numpy as np

li = [1,2,3,'a']

a = np.array(li)

b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
rn = np.random.randint(0,100, size =10)
rn

array([31, 23, 65, 27, 64, 78, 59, 67, 77, 80])

In [17]:


m3 = np.random.randint(0,10, size = (3,3,3,3))
m3[2][2][2][1]

8

In [25]:
m3.ndim # dimension of array
m3.size # len of elemenst
m3.shape # dimensions in array list
m3.dtype # 32 or 64 bit 
m3.itemsize # bytes
m3.nbytes

324

In [26]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [30]:
c=b.reshape(5,3)

In [43]:
d = c + 1
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [40]:
l=[1,3,2,3,4,5,6,7,8,9]
x1,x2,x3=np.split(l,[3,5])
print(x1,x2,x3)

[1 3 2] [3 4] [5 6 7 8 9]


In [ ]:
import numpy as np
a = np.

### Pandas
**Use Cases**
- Data Cleaning
- Data Transformation
- Data Analysis

**Notations**
- Series
- DataFrames

In [50]:
import pandas as pd

internal1 = {'s1':21,'s2':18,'s3':24}

internal1 = pd.Series(internal1)

internal1

internal2 = {'s1':15,'s2':18,'s3':12,'s4':13}

internal2 = pd.Series(internal2)

internal2

s1    15
s2    18
s3    12
s4    13
dtype: int64

In [51]:
final = {'Internal1':internal1, 'Internal2':internal2}
final = pd.DataFrame(final)
final

Internal1  Internal2
s1       21.0         15
s2       18.0         18
s3       24.0         12
s4        NaN         13

In [12]:
final.columns # list of all columns

Index(['Internal1', 'Internal2'], dtype='object')

In [24]:
final.values # list of all rows

array([[21., 15.],
       [18., 18.],
       [24., 12.],
       [nan, 13.]])

In [21]:
final.values[3]

array([nan, 13.])

In [22]:
final.values[2,0]

24.0

In [26]:
final.values[2][0]

24.0

In [29]:
for row in final.values:
    print('Internal1 - ',row[0],', Internal2 - ',row[1])

Internal1 -  21.0 , Internal2 -  15.0
Internal1 -  18.0 , Internal2 -  18.0
Internal1 -  24.0 , Internal2 -  12.0
Internal1 -  nan , Internal2 -  13.0


In [30]:
final

Internal1  Internal2
s1       21.0         15
s2       18.0         18
s3       24.0         12
s4        NaN         13

In [33]:
final.loc['s3'] = [15,19]

In [34]:
final

Internal1  Internal2
s1       21.0         15
s2       18.0         18
s3       15.0         19
s4        NaN         13
3        15.0         19

In [38]:
final.drop(3)

Internal1  Internal2
s1       21.0         15
s2       18.0         18
s3       15.0         19
s4        NaN         13

In [54]:
final.loc['s4'] = [15,24]

In [45]:
final = final.drop(3)

In [55]:
final

Internal1  Internal2
s1       21.0         15
s2       18.0         18
s3       24.0         12
s4       15.0         24

In [58]:
# Reading CSV File Data
import pandas as pd
incomedf =  pd.read_csv('DataFiles/income.csv')
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [63]:
# Extract income of all states in 2013
for i in incomedf.values:
    print(i[1], ':', i[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [68]:
# Average Income of Arizona

sum = 0
for i in range(2,11):
    sum += incomedf.values[2][i]
print(sum/len(incomedf.values[2][2:]))

47214.77777777778


In [71]:
# Avg income of all states in 2012
sum = 0
for i in incomedf.values:
    sum +=i[-2]
print(sum/len(incomedf.values))

50038.8
